# These are supported funding model platforms

github: # luishubp 
patreon: # 
open_collective: # 
ko_fi: # MidNighthubp 
liberapay: # 
issuehunt: # 
polar: # 
buy_me_a_coffee: # MidNighthubp 
custom: #  https://nubank.com.br/cobrar/00020126330014BR.GOV.BCB.PIX01111005809356752040000530398654045.005802BR5925Luis Gabriel Santos Mende6009SAO PAULO62140510bPTVOMVe2j63044D86
